spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forum
    username: <username>
    password: <password>
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate
  main:
    banner-mode: off
  session:
    store-type: none
  lifecycle:
    timeout-per-shutdown-phase: 60
  security:
    filter:
      order: 5
  profiles:
    active: '@activatedProfile@'
    default: tomcat
  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  address: localhost
  port: 8080
  servlet:
    session:
      cookie:
        secure: true
        path: /
      timeout: 600
    context-path: /
  shutdown: graceful

logging:
  level:
    org.springframework.web.servlet.resource: error
    reactor.netty.http.client: debug